version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  mosquitto:
    image: eclipse-mosquitto:1.6.3
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/users:/mosquitto/config/users
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always
    user: '1000:1000'

  influxdb:
    image: influxdb:1.7.7
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:6.2.5
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
    restart: always
    user: '1000:1000'

  
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./hass/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    user: '1000:1000'

  # mqttbridge:
  #   build: ./bridge
  #   image: nilhcem/mqttbridge
  #   container_name: mqttbridge
  #   depends_on:
  #     - mosquitto
  #     - influxdb
  #   restart: always
